const countryCodeMap = {
    "South Korea": "kr",
    "대한민국": "kr",
    "United States": "us",
    "미국": "us",
    "Japan": "jp",
    "일본": "jp",
    "China": "cn",
    "중국": "cn",
    "Philippines": "ph",
    "필리핀": "ph",
    "France": "fr",
    "프랑스": "fr",
    "Germany": "de",
    "독일": "de",
    "United Kingdom": "gb",
    "영국": "gb",
    "Canada": "ca",
    "캐나다": "ca",
    "Russia": "ru",
    "러시아": "ru",
    "Australia": "au",
    "호주": "au",
    "India": "in",
    "인도": "in",
    "Brazil": "br",
    "브라질": "br",
    "Italy": "it",
    "이탈리아": "it",
    "Spain": "es",
    "스페인": "es",
    "Mexico": "mx",
    "멕시코": "mx",
    "Vietnam": "vn",
    "베트남": "vn",
    "Thailand": "th",
    "태국": "th",
    "Indonesia": "id",
    "인도네시아": "id",
    "Malaysia": "my",
    "말레이시아": "my",
    "Singapore": "sg",
    "싱가포르": "sg",
    "Pakistan": "pk",
    "파키스탄": "pk",
    "Bangladesh": "bd",
    "방글라데시": "bd",
    "Egypt": "eg",
    "이집트": "eg",
    "Saudi Arabia": "sa",
    "사우디아라비아": "sa",
    "Turkey": "tr",
    "터키": "tr",
    "Israel": "il",
    "이스라엘": "il",
    "Argentina": "ar",
    "아르헨티나": "ar",
    "Colombia": "co",
    "콜롬비아": "co",
    "Chile": "cl",
    "칠레": "cl",
    "South Africa": "za",
    "남아프리카 공화국": "za",
    "Nigeria": "ng",
    "나이지리아": "ng",
    "Kenya": "ke",
    "케냐": "ke",
    "Greece": "gr",
    "그리스": "gr",
    "Sweden": "se",
    "스웨덴": "se",
    "Norway": "no",
    "노르웨이": "no",
    "Denmark": "dk",
    "덴마크": "dk",
    "Netherlands": "nl",
    "네덜란드": "nl",
    "Switzerland": "ch",
    "스위스": "ch",
    "Portugal": "pt",
    "포르투갈": "pt",
    "Poland": "pl",
    "폴란드": "pl",
    "Czech Republic": "cz",
    "체코": "cz",
    "Austria": "at",
    "오스트리아": "at",
    "Finland": "fi",
    "핀란드": "fi",
    "Hungary": "hu",
    "헝가리": "hu",
    "New Zealand": "nz",
    "뉴질랜드": "nz",
    "Taiwan": "tw",
    "대만": "tw",
    "Hong Kong": "hk",
    "홍콩": "hk",
    "North Korea": "kp",
    "북한": "kp",
  };
  
  export default countryCodeMap;
  